-- ============================================================================
-- seed/02_topics.sql — 오늘의 토픽 시드 (mockData.ts > todayTopicsSeed 동등)
-- slug 로 중복 방지. publish_kst_day 는 오늘로 채움.
-- ============================================================================

with t(slug, category_id, title, description, news_url, news_source, heat) as (values
  ('society-1', 'society'::public.category_id, '따릉이 음주운전 사건, 어떻게 생각하시나요?',
   '최근 따릉이(공공자전거)를 음주 상태에서 운전하다 보행자를 다치게 한 사건이 발생했습니다.',
   'https://news.example.com/article/12345', '한겨레', 982),
  ('politics-1','politics','국회의원 면책특권 축소, 찬성하시나요?',
   '여야가 면책특권 범위를 명예훼손·허위사실 발언까지 제한하는 개정안을 두고 논의 중입니다.',
   'https://news.example.com/article/22221', '연합뉴스', 743),
  ('tech-1','tech','AI 코드 리뷰가 시니어를 대체할 수 있을까?',
   'GPT-5 기반 코드 리뷰 봇이 시니어 엔지니어 PR 리뷰 정확도를 92%까지 따라잡았습니다.',
   'https://news.example.com/article/33331', 'ZDNet Korea', 612),
  ('economy-1','economy','주식 양도세 전면 도입, 시장에 미칠 영향은?',
   '2027년부터 주식 양도세가 전면 시행될 예정입니다.',
   'https://news.example.com/article/44441', '매일경제', 488),
  ('culture-1','culture','OTT 자막 번역, AI에게 맡겨도 될까?',
   '주요 OTT 플랫폼이 AI 자막 번역 비중을 70%까지 확대했습니다.',
   'https://news.example.com/article/55551', '씨네21', 321),
  ('sports-1','sports','프로야구 로봇 심판, 전면 도입해야 할까?',
   'ABS 정확도가 99%를 넘었지만, 경기의 인간미와 변수도 함께 사라진다는 지적이 나옵니다.',
   'https://news.example.com/article/66661', '스포츠동아', 256),
  ('society-2','society','택배 분리수거 의무화, 소비자가 부담해야 할까?',
   '환경부가 택배 박스 분리수거를 소비자 책임으로 전환하는 방안을 검토 중입니다.',
   'https://news.example.com/article/12346', '한겨레', 540),
  ('society-3','society','노키즈존 합법화 논쟁, 어디까지 허용?',
   '사업주의 영업의 자유와 차별 금지 사이 균형이 다시 도마에 올랐습니다.',
   'https://news.example.com/article/12347', '경향신문', 410),
  ('politics-2','politics','선거연령 16세 인하, 시기상조일까?',
   '청소년 정치참여 확대와 정치적 성숙도 사이의 논쟁이 다시 점화됐습니다.',
   'https://news.example.com/article/22222', '연합뉴스', 520),
  ('politics-3','politics','지방의회 의원 정수 축소, 효율인가 후퇴인가?',
   '행안부가 인구 감소 지역 의원 정수 축소를 권고했습니다.',
   'https://news.example.com/article/22223', '한겨레', 280),
  ('tech-2','tech','오픈소스 LLM 상업적 이용 제한, 어떻게 봐야 할까?',
   '주요 오픈소스 모델들이 라이선스를 상업적 제한으로 전환했습니다.',
   'https://news.example.com/article/33332', 'ZDNet Korea', 470),
  ('tech-3','tech','주니어 개발자 채용 빙하기, 돌파구는?',
   'AI 코딩 도구 보급 이후 주니어 채용이 급감했습니다.',
   'https://news.example.com/article/33333', '전자신문', 360),
  ('economy-2','economy','재택근무 세제 혜택 폐지, 기업 자율로?',
   '한시적으로 운영해온 재택근무 세제 혜택의 일몰 여부를 두고 의견이 갈립니다.',
   'https://news.example.com/article/44442', '매일경제', 300),
  ('economy-3','economy','1인 가구 주택담보대출 우대, 형평성 논란',
   '1인 가구 전용 LTV 우대안이 다인 가구 역차별이라는 비판을 받습니다.',
   'https://news.example.com/article/44443', '한국경제', 220),
  ('culture-2','culture','K-팝 굿즈 가격 인상, 팬덤은 어디까지 감당?',
   '주요 기획사들이 굿즈 가격을 평균 18% 인상했습니다.',
   'https://news.example.com/article/55552', '씨네21', 240),
  ('culture-3','culture','AI 생성 웹툰, 작가 표기 의무화 필요할까?',
   'AI 보조 작화 비중이 늘면서 창작자 표기와 저작권 표시 기준이 새 쟁점이 됐습니다.',
   'https://news.example.com/article/55553', '조선일보', 195),
  ('sports-2','sports','프로축구 승강제 확대, K리그 흥행 카드일까?',
   'K리그2와의 승강제 확대 논의가 흥행과 안정성 사이에서 평행선을 달리고 있습니다.',
   'https://news.example.com/article/66662', '스포츠동아', 180),
  ('sports-3','sports','e스포츠 정식 종목 채택, 어디까지 인정?',
   '아시안게임 이후 e스포츠 정식 종목 확대 범위를 두고 의견이 엇갈립니다.',
   'https://news.example.com/article/66663', 'OSEN', 145)
)
insert into public.topics (slug, category_id, title, description, news_url, news_source, heat, source)
select slug, category_id, title, description, news_url, news_source, heat, 'seed'
  from t
on conflict (slug) do update set
  title       = excluded.title,
  description = excluded.description,
  news_url    = excluded.news_url,
  news_source = excluded.news_source,
  heat        = excluded.heat;
